Aggiunto metodo getAllErrors(), restituisce tutti gli errori sotto forma di array
Slamdunk/php-validatore-fattura-elettronica pull request #43
Opened 2023-09-13 10:33 UTC by ToX82

Per alcuni utilizzi può essere utile ottenere un array contenente tutti gli errori, invece di un'eccezione al primo errore rilevato. Questa pull request aggiunge questa funzionalità. Ho aggiornato il file README.md con un esempio di utilizzo.

2023-12-13 09:34 UTC, GrassoFederico commented
Questa funzionalità sarebbe veramente comoda da utilizzare!

2023-12-14 11:16 UTC, Slamdunk requested changes
Mancano nella lista degli errori quelli ricavati dalla chiamata `$dom->loadXML($xml);` senza il flag `\LIBXML_NOERROR`.

Se riesci ad aggiungere anche questi, e a riutilizzare il nuovo codice in `assertValidXml` così da evitare duplicazioni, si può fare il merge.

2023-12-16 18:33 UTC, ToX82 commented
Non sono sicuro di aver capito la seconda parte della richiesta, ma ho aggiunto la validazione senza il flag \LIBXML_NOERROR al mio metodo, ed aggiunto il relativo test. Può andare bene così?

2023-12-21 15:35 UTC, Slamdunk commented
Merge effettuato in https://github.com/Slamdunk/php-validatore-fattura-elettronica/pull/47, grazie mille

2023-12-21 15:35 UTC, closed without merging

2023-12-21 15:36 UTC, Slamdunk commented
Rilasciato in [`v1.2.1-patch20231221.1`](https://github.com/Slamdunk/php-validatore-fattura-elettronica/releases/tag/v1.2.1-patch20231221.1).